---
version: "3"
services:
  rmq:
    container_name: rmq
    image: ghcr.io/incuvers/rabbitmq:arm64
    ports:
      # expose for rmq management client
      - "15672:15672"
    networks:
      - amqp

  hwi:
    container_name: hwi
    depends_on:
      - rmq
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
      - /sys:/sys
    networks:
      - amqp
    environment:
      - RABBITMQ_ADDR=rmq:5672
      - HWI_LOGS=/app/instance/logs
      - HWI_CERTS=/app/instance/certs

networks:
  amqp:
