---
version: "3"
services:
  rmq:
    container_name: rmq
    image: ghcr.io/incuvers/rabbitmq:arm64
    ports:
      # expose for rmq management client
      - "15672:15672"
    networks:
      - amqp
      - loki
  grafana:
    image: ghcr.io/incuvers/grafana:latest
    container_name: grafana
    # restart: always
    user: "1000"
    ports:
      - "3000:3000"
    # volumes:
    #   # define persistant volumes
    #   - ~/.grafana/data:/var/lib/grafana
    #   - ~/.grafana/provisioning:/etc/grafana/provisioning 
    networks:
      - loki
  hwi:
    container_name: hwi
    depends_on:
      - rmq
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
      - /sys:/sys
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    networks:
      - amqp
    environment:
      - RABBITMQ_ADDR=rmq:5672
      - HWI_SERIAL=/dev/ttyUSB0
      - HWI_LOGS=/app/instance/logs
      - HWI_CERTS=/app/instance/certs

networks:
  amqp:
  loki:
