version: "2.9"
services:
  rmq:
    container_name: rmq
    image: rabbitmq:3.9-management
    volumes:
      - "rabbitmq/:/etc/rabbitmq/"

  hwi:
    container_name: hwi
    depends_on:
      - rmq
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    environment:
      - RABBITMQ_ADDR=rmq:5672
