version: "2.9"
services:
  rmq:
    container_name: rmq
    image: rabbitmq:3.9-management
    volumes:
      - "./rabbitmq/:/etc/rabbitmq/"
    ports:
      # expose for rmq web client
      - "15672:15672"
    networks:
      - iris 

  hwi:
    container_name: hwi
    depends_on:
      - rmq
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
      - /sys:/sys
    networks:
      - iris 
    environment:
      - RABBITMQ_ADDR=rmq:5672

networks:
  iris: