---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
    type: [opened, synchronized, re-opened]
    branches:
      - master

jobs:
  unittest:
    name: unittest suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Install dependancies
        run: |
          sudo apt update
          sudo apt install git
          xargs -a apt-packages.txt sudo apt install -y
          python3 -m pip install -r requirements.txt
          ./scripts/tis-install.sh
      - name: Run unittest suite
        run: make unit
  lint:
    name: lint suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Install dependancies
        run: |
          python3 -m pip install flake8
          touch .env
      - name: Run lint directive
        run: make lint
